<h1>EE 520 Homework 3</h1>
<h2>Neema Badihian</h2>
<h2>09/16/2021</h2>

In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
M1 = np.array([[np.exp((2j*np.pi) / 10)**(-4), 0], [0, np.exp((2j*np.pi) / 10)**(3)]])

In [3]:
ZT = np.array([[1 / ((1 + np.sqrt(5)) / 2), 1 / ((1 + np.sqrt(5)) / 2)],
               [1 / ((1 + np.sqrt(5)) / 2), -1 / ((1 + np.sqrt(5)) / 2)]])

In [4]:
M2 = la.multi_dot([ZT, M1, ZT])

In [5]:
M1

array([[-0.80901699-0.58778525j,  0.        +0.j        ],
       [ 0.        +0.j        , -0.30901699+0.95105652j]])

In [6]:
M2

array([[-0.42705098+0.13875728j, -0.19098301-0.58778525j],
       [-0.19098301-0.58778525j, -0.42705098+0.13875728j]])

In [7]:
M1i = la.inv(M1)

In [8]:
M2i = la.inv(M2)

In [9]:
M1i

array([[-0.80901699+0.58778525j, -0.        +0.j        ],
       [ 0.        -0.j        , -0.30901699-0.95105652j]])

In [10]:
M2i

array([[-0.73176275-0.23776413j, -0.32725425+1.00718501j],
       [-0.32725425+1.00718501j, -0.73176275-0.23776413j]])

In [11]:
allArr = np.array([M1, M2, M1i, M2i])

In [12]:
ans = None
ansFound = False
numOfMults = 10
multStr = ""
for i in range(allArr[0].size):
    for j in range(allArr[0].size):
        ans = la.multi_dot([allArr[i], allArr[j]])
        if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 2:
            numOfMults = 2
            ansFound = True
            multStr = f"i = {i}, j = {j}"
            break
        for k in range(allArr[0].size):
            ans = la.multi_dot([allArr[i], allArr[j], allArr[k]])
            if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 3:
                numOfMults = 3
                multStr = f"i = {i}, j = {j}, k = {k}"
                break
            for l in range(allArr[0].size):
                ans = la.multi_dot([allArr[i], allArr[j], allArr[k], allArr[l]])
                if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 4:
                    numOfMults = 4
                    multStr = f"i = {i}, j = {j}, k = {k}, l = {l}"
                    break
                for m in range(allArr[0].size):
                    ans = la.multi_dot([allArr[i], allArr[j], allArr[k], allArr[l], allArr[m]])
                    if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 5:
                        numOfMults = 5
                        multStr = f"i = {i}, j = {j}, k = {k}, l = {l}, m = {m}"
                        break
                    for n in range(allArr[0].size):
                        ans = la.multi_dot([allArr[i], allArr[j], allArr[k], allArr[l], allArr[m], allArr[n]])
                        if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 6:
                            numOfMults = 6
                            multStr = f"i = {i}, j = {j}, k = {k}, l = {l}, m = {m}, n = {n}"
                            break
                        for x in range(allArr[0].size):
                            ans = la.multi_dot([allArr[i], allArr[j], allArr[k], allArr[l], allArr[m], allArr[n],
                                                allArr[x]])
                            if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 7:
                                numOfMults = 7
                                multStr = f"i = {i}, j = {j}, k = {k}, l = {l}, m = {m}, n = {n}, x = {x}"
                                break
                            for y in range(allArr[0].size):
                                ans = la.multi_dot([allArr[i], allArr[j], allArr[k], allArr[l], allArr[m], allArr[n],
                                                    allArr[x], allArr[y]])
                                if np.abs(ans[0,0]) < 0.000001 and np.abs(ans[1,1]) < 0.000001 and numOfMults > 8:
                                    numOfMults = 8
                                    multStr = f"i = {i}, j = {j}, k = {k}, l = {l}, m = {m}, n = {n}, x = {x}, y = {y}"
                                    break

print(multStr)

i = 1, j = 1, k = 1, l = 1, m = 1


In [13]:
la.multi_dot([M2, M2, M2, M2, M2])

array([[-1.31838984e-16+5.55111512e-17j,  2.60179800e-01-5.20417043e-17j],
       [ 2.60179800e-01-5.20417043e-17j, -1.31838984e-16+5.55111512e-17j]])