In [3]:
import numpy as np

<h2>Part A</h2>

In [4]:
def initialize0s(n):
    O = np.zeros((2**n, 1)) ## create a zero vector with 2**n rows and 1 column
    O[0][0] = 1 ## set the first value in the vector to 1
    return O

print(f"|0^1>\n------\n{initialize0s(1)}\n")
print(f"|0^2>\n------\n{initialize0s(2)}\n")
print(f"|0^3>\n------\n{initialize0s(3)}\n")

|0^1>
------
[[1.]
 [0.]]

|0^2>
------
[[1.]
 [0.]
 [0.]
 [0.]]

|0^3>
------
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]



<h2>Part B</h2>

In [5]:
def cnot(i, j, n):
    if i == j or i > n or j > n: return None
    X = np.zeros((2**n, 2**n))
    for k in range(2**n):
        if k & (1 << (n - i)): ## check if qubit i of current index is active
            m = k ^ (1 << (n - j)) ## flip the qubit j of current index
        else:
            m = k ## the identity
        X[m, k] = 1
    return X

In [6]:
print(f"i = 2, j = 1, n = 2\n----------------\n{cnot(2, 1, 2)}\n")
print(f"i = 1, j = 2, n = 3\n----------------\n{cnot(1, 2, 2)}\n")

i = 2, j = 1, n = 2
----------------
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

i = 1, j = 2, n = 3
----------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]



In [7]:
print(f"i = 3, j = 2, n = 3\n----------------\n{cnot(3, 2, 3)}\n")
print(f"i = 3, j = 4, n = 3\n----------------\n{cnot(2, 3, 3)}\n")

i = 3, j = 2, n = 3
----------------
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]

i = 3, j = 4, n = 3
----------------
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]



<h2>Part C</h2>

In [15]:
def unitary1(U, j, n):
    if j == 1:
        U1 = U
    else:
        U1 = np.identity(2)

    for i in range(n):
        if i > 0 and i+1 == j:
            U1 = np.kron(U1, U)
        elif i > 0 and i+1 != j:
            U1 = np.kron(U1, np.identity(2))
    
    return U1

In [16]:
test = unitary1(cnot(1, 2, 2), 2, 2)

In [17]:
test

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])