In [1]:
import numpy as np
import math
from scipy.linalg import expm

<h1>Part A</h1>

In [28]:
initial_state = np.zeros((16, 1))
initial_state[0][0] = 1

In [3]:
X_gate = np.array([[0, 1], [1, 0]])

In [4]:
X_2 = np.kron(X_gate, X_gate)

In [5]:
e_gate = expm((1.0j * 0.1475835 * math.pi) * X_2)

In [6]:
e_gate

array([[0.89442736+0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        +0.44721326j],
       [0.        +0.j        , 0.89442736+0.j        ,
        0.        +0.44721326j, 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.44721326j,
        0.89442736+0.j        , 0.        +0.j        ],
       [0.        +0.44721326j, 0.        +0.j        ,
        0.        +0.j        , 0.89442736+0.j        ]])

In [7]:
e_2 = np.kron(e_gate, e_gate)

In [8]:
result = np.matmul(e_2, initial_state)

In [9]:
ident = np.array([[1, 0], [0, 1]])
ident

array([[1, 0],
       [0, 1]])

In [10]:
result = np.matmul(np.kron(ident, np.kron(e_gate, ident)), result)

In [11]:
result

array([[ 0.71554215+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.35777074j],
       [ 0.        +0.j        ],
       [-0.17888521+0.j        ],
       [ 0.        +0.35777074j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        -0.08944252j],
       [-0.17888521+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.35777074j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.17888521+0.j        ]])

In [12]:
CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])

In [13]:
result = np.matmul(np.kron(CNOT, e_gate), result)

In [14]:
result

array([[ 0.48000065+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.63999988j],
       [ 0.        +0.j        ],
       [-0.31999965+0.j        ],
       [ 0.        +0.2400001j ],
       [ 0.        +0.j        ],
       [ 0.        +0.2400001j ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.31999965+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        -0.15999967j],
       [-0.11999994+0.j        ],
       [ 0.        +0.j        ]])

In [15]:
answer_a = result[0][0]**2

In [16]:
answer_a

(0.2304006244930291+0j)

<h1>Part B</h1>

In [17]:
sum = 0
for i in range(8):
    sum += abs(result[8+i][0]**2)

In [18]:
sum

0.19999970431229258

In [19]:
answer_b = abs(result[8][0]**2)/sum

<h1>Part C</h1>

In [20]:
result_trans = np.transpose(result)

In [21]:
result_trans_conj = np.conjugate(result_trans)

In [22]:
result_trans_conj

array([[ 0.48000065-0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.63999988j,
         0.        -0.j        , -0.31999965-0.j        ,
         0.        -0.2400001j ,  0.        -0.j        ,
         0.        -0.2400001j ,  0.        -0.j        ,
         0.        -0.j        , -0.31999965-0.j        ,
         0.        -0.j        ,  0.        +0.15999967j,
        -0.11999994-0.j        ,  0.        -0.j        ]])

In [23]:
density_matr = np.matmul(result, result_trans_conj)

In [24]:
len(density_matr[0])

16

In [25]:
trace1 = 0
trace2 = 0
trace3 = 0
trace4 = 0
for i in range(8):
    trace1 += density_matr[i][i]
    trace2 += density_matr[i][i+8]
    trace3 += density_matr[i+8][i]
    trace4 += density_matr[i+8][i+8]

In [26]:
density_tr = np.array([[trace1, trace2], [trace3, trace4]])

In [27]:
density_tr

array([[0.8000003+0.j        , 0.       -0.39999978j],
       [0.       +0.39999978j, 0.1999997+0.j        ]])